prefix afn: <http://jena.hpl.hp.com/ARQ/function#>
prefix fn: <http://www.w3.org/2005/xpath-functions#>
prefix rdfh: <http://lod2.eu/schemas/rdfh#> 
prefix qb: <http://purl.org/linked-data/cube#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

select
       ((100 * sum(xsd:integer(fn:starts-with(?p_type, "PROMO")) * (?l_lineextendedprice) *  ((1) - (?l_linediscount)))  / sum((?l_lineextendedprice) *  ((1) - (?l_linediscount)))) as ?promo_revenue)
where
{

    ?li 
        rdfh:l_lineextendedprice ?l_lineextendedprice ;
        rdfh:l_linediscount ?l_linediscount ;
        rdfh:l_shipdate ?l_shipdate ;
        rdfh:l_has_partsupplier ?ps .
    ?ps rdfh:ps_has_part ?part .
    ?part rdfh:p_type ?p_type .
    filter (xsd:date(?l_shipdate) >= xsd:date("1997-08-01"^^xsd:date) &&
      (xsd:date(?l_shipdate) < xsd:date("1997-08-01"^^xsd:date + "P1M"^^xsd:duration)) )

}
